<?php

/**
 * @file
 * Contains permit_application.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function permit_application_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.permit_application':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for handling permit application submissions with API integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function permit_application_theme($existing, $type, $theme, $path) {
  return [
    'permit_application_page' => [
      'variables' => [
        'form' => NULL,
      ],
      'template' => 'permit-application-page',
    ],
  ];
}
