<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * Main module file for Établissements pharmaceutiques.
 */

/**
 * Implements hook_help().
 */
function etablissements_pharmaceutiques_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.etablissements_pharmaceutiques':
      return t('Module for managing pharmaceutical establishments.');
  }
}
